/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai-tools',
    path: '/ai-tools',
    component: 'layout.base',
    meta: {
      title: 'ai-tools',
      i18nKey: 'route.ai-tools',
      icon: 'mdi:robot',
      order: 3
    },
    children: [
      {
        name: 'ai-tools_token',
        path: '/ai-tools/token',
        component: 'view.ai-tools_token',
        meta: {
          title: 'ai-tools_token',
          i18nKey: 'route.ai-tools_token',
          icon: 'mdi:key'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'localfile',
    path: '/localfile',
    component: 'layout.base',
    meta: {
      title: 'localfile',
      i18nKey: 'route.localfile',
      icon: 'mdi:folder',
      order: 2
    },
    children: [
      {
        name: 'localfile_ebook',
        path: '/localfile/ebook',
        component: 'view.localfile_ebook',
        meta: {
          title: 'ebook',
          i18nKey: 'route.localfile_ebook',
          icon: 'mdi:book'
        }
      },
      {
        name: 'localfile_large-media',
        path: '/localfile/large-media',
        component: 'view.localfile_large-media',
        meta: {
          title: 'large-media',
          i18nKey: 'route.localfile_large-media',
          icon: 'mdi:folder-video'
        }
      },
      {
        name: 'localfile_multimedia',
        path: '/localfile/multimedia',
        component: 'view.localfile_multimedia',
        meta: {
          title: 'multimedia',
          i18nKey: 'route.localfile_multimedia',
          icon: 'mdi:image-multiple'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:settings',
      order: 4,
      roles: ['ADMIN']
    },
    children: [
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'mdi:shield-account'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-group'
        }
      }
    ]
  }
];
