package com.yuyutian.mytools.dshconnector.service;import com.fasterxml.jackson.databind.ObjectMapper;import com.yuyutian.mytools.dshconnector.model.DshModels.*;import com.yuyutian.mytools.dshconnector.repository.DshSessionRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Instant;import java.util.*;
/** DSH 会话服务。 */ @Service public class DshSessionService {private final DshSessionRepository repository;private final ObjectMapper mapper;/** 创建服务。 @param repository 仓储 @param mapper JSON */ public DshSessionService(DshSessionRepository repository,ObjectMapper mapper){this.repository=repository;this.mapper=mapper;}
 /** 迁移旧绑定。 @param batch 批次 @return 结果 */ @Transactional public MigrationResult migrate(MigrationBatch batch){int accepted=0,skipped=0,rejected=0;Set<Long>seen=new HashSet<>();MessageDigest collection=sha256();for(LegacyBinding item:batch.items()){String digest=digest(item);update(collection,Long.toString(item.legacyId()),digest);if(!seen.add(item.legacyId())){skipped++;continue;}String existing=repository.digest(item.legacyId());if(existing==null){accepted++;if(!batch.dryRun())repository.insert(batch.migrationKey(),item,digest,Instant.now());}else if(existing.equals(digest))skipped++;else rejected++;}return new MigrationResult(batch.dryRun(),accepted,skipped,rejected,HexFormat.of().formatHex(collection.digest()));}
 /** 查询所有者会话。 @param ownerId 所有者 @return 会话 */ @Transactional(readOnly=true) public List<BindingView> list(long ownerId){return repository.list(ownerId);}
 /** 推进会话序号。 @param ownerId 所有者 @param sessionId 会话 @param sequence 序号 */ @Transactional public void advance(long ownerId,String sessionId,long sequence){if(sequence<0||!repository.advance(ownerId,sessionId,sequence,Instant.now()))throw new IllegalArgumentException("dsh session is invalid");}
 /** 归档会话。 @param ownerId 所有者 @param sessionId 会话 */ @Transactional public void archive(long ownerId,String sessionId){if(!repository.archive(ownerId,sessionId,Instant.now()))throw new IllegalArgumentException("dsh session is invalid");}
 /** 对账迁移。 @param key 迁移键 @return 对账 */ @Transactional(readOnly=true) public Reconciliation reconcile(String key){List<String>values=repository.evidence(key);MessageDigest digest=sha256();for(String value:values){String[]parts=value.split("\\|",2);update(digest,parts[0],parts[1]);}return new Reconciliation(values.size(),HexFormat.of().formatHex(digest.digest()));}
 private String digest(Object value){try{return HexFormat.of().formatHex(sha256().digest(mapper.writeValueAsBytes(value)));}catch(java.io.IOException exception){throw new IllegalStateException("dsh digest failed",exception);}}
 private MessageDigest sha256(){try{return MessageDigest.getInstance("SHA-256");}catch(NoSuchAlgorithmException exception){throw new IllegalStateException("SHA-256 unavailable",exception);}}
 private void update(MessageDigest digest,String...values){for(String value:values){byte[]data=value.getBytes(StandardCharsets.UTF_8);digest.update(ByteBuffer.allocate(4).putInt(data.length).array());digest.update(data);}}
}
