package com.yuyutian.mytools.dshconnector.repository;import com.yuyutian.mytools.dshconnector.model.DshModels.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.sql.Timestamp;import java.time.Instant;import java.util.*;
/** DSH 会话仓储。 */ @Repository public class DshSessionRepository {private final JdbcTemplate jdbc;/** 创建仓储。 @param jdbc JDBC */ public DshSessionRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 /** 查询迁移摘要。 @param legacyId 旧标识 @return 摘要 */ public String digest(long legacyId){return jdbc.query("SELECT payload_sha256 FROM dsh_session_migration WHERE legacy_id=?",(rs,row)->rs.getString(1),legacyId).stream().findFirst().orElse(null);}
 /** 写入旧绑定。 @param key 迁移键 @param item 绑定 @param digest 摘要 @param now 时间 */ public void insert(String key,LegacyBinding item,String digest,Instant now){String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO dsh_session_binding VALUES (?,?,?,?,?,?,?,?,?)",id,item.legacyId(),item.ownerId(),item.dshSessionId(),item.workspaceKey(),item.status(),item.lastSequence(),Timestamp.from(item.createdAt()),Timestamp.from(item.updatedAt()));jdbc.update("INSERT INTO dsh_session_migration VALUES (?,?,?,?,?)",item.legacyId(),key,digest,id,Timestamp.from(now));}
 /** 查询用户会话。 @param ownerId 所有者 @return 会话 */ public List<BindingView> list(long ownerId){return jdbc.query("SELECT * FROM dsh_session_binding WHERE owner_id=? AND status<>'ARCHIVED' ORDER BY updated_at DESC,id",(rs,row)->view(rs),ownerId);}
 /** 单调更新事件序号。 @param ownerId 所有者 @param sessionId 会话 @param sequence 序号 @param now 时间 @return 是否存在 */ public boolean advance(long ownerId,String sessionId,long sequence,Instant now){return jdbc.update("UPDATE dsh_session_binding SET last_sequence=CASE WHEN last_sequence<? THEN ? ELSE last_sequence END,updated_at=? WHERE owner_id=? AND dsh_session_id=?",sequence,sequence,Timestamp.from(now),ownerId,sessionId)==1;}
 /** 归档会话。 @param ownerId 所有者 @param sessionId 会话 @param now 时间 @return 是否存在 */ public boolean archive(long ownerId,String sessionId,Instant now){return jdbc.update("UPDATE dsh_session_binding SET status='ARCHIVED',updated_at=? WHERE owner_id=? AND dsh_session_id=?",Timestamp.from(now),ownerId,sessionId)==1;}
 /** 返回迁移证据。 @param key 迁移键 @return 证据 */ public List<String> evidence(String key){return jdbc.query("SELECT legacy_id,payload_sha256 FROM dsh_session_migration WHERE migration_key=? ORDER BY legacy_id",(rs,row)->rs.getLong(1)+"|"+rs.getString(2),key);}
 private BindingView view(java.sql.ResultSet rs)throws java.sql.SQLException{return new BindingView(UUID.fromString(rs.getString("id")),(Long)rs.getObject("legacy_id"),rs.getLong("owner_id"),rs.getString("dsh_session_id"),rs.getString("workspace_key"),rs.getString("status"),rs.getLong("last_sequence"),rs.getTimestamp("created_at").toInstant(),rs.getTimestamp("updated_at").toInstant());}
}
