package com.yuyutian.mytools.gateway.service;

import com.yuyutian.mytools.gateway.config.GatewayProperties;import com.yuyutian.mytools.gateway.model.MessagingGatewayModels.*;import org.springframework.http.*;import org.springframework.stereotype.Component;import org.springframework.web.client.*;import org.springframework.web.util.UriComponentsBuilder;import java.util.UUID;
/** Messaging 内部客户端。 */ @Component public class MessagingGatewayClient {private final RestTemplate template;private final GatewayProperties properties;
 /** 创建客户端。 @param template HTTP 模板 @param properties 配置 */ public MessagingGatewayClient(RestTemplate template,GatewayProperties properties){this.template=template;this.properties=properties;}
 /** 分页查询消息。 @param ownerId 所有者 @param afterId 游标 @param limit 数量 @param correlationId 关联标识 @return 消息页 */ public MessagePage list(long ownerId,UUID afterId,int limit,String correlationId){UriComponentsBuilder builder=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/inbound-messages").queryParam("ownerId",ownerId).queryParam("limit",limit);if(afterId!=null)builder.queryParam("afterId",afterId);return exchange(builder.toUriString(),MessagePage.class,correlationId);}
 /** 查询消息。 @param ownerId 所有者 @param id 消息 @param correlationId 关联标识 @return 消息 */ public MessageView view(long ownerId,UUID id,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/inbound-messages/"+id).queryParam("ownerId",ownerId).toUriString();return exchange(url,MessageView.class,correlationId);}
 private <T>T exchange(String url,Class<T>type,String correlationId){try{T value=template.exchange(url,HttpMethod.GET,entity(correlationId),type).getBody();if(value==null)throw new GatewayDownstreamException();return value;}catch(HttpStatusCodeException exception){if(exception.getStatusCode().value()==404)throw new GatewayNotFoundException();if(exception.getStatusCode().is4xxClientError())throw new GatewayBadRequestException();throw new GatewayDownstreamException();}catch(ResourceAccessException exception){throw new GatewayDownstreamException();}}
 private HttpEntity<Void> entity(String correlationId){if(properties.messagingToken()==null||properties.messagingToken().isBlank())throw new GatewayUnauthorizedException();HttpHeaders headers=new HttpHeaders();headers.setBearerAuth(properties.messagingToken());headers.set("X-Correlation-Id",correlationId);return new HttpEntity<>(headers);}
 private String root(){return properties.messagingUrl().replaceAll("/+$","");}
}
