package com.yuyutian.mytools.gateway.service;

import com.yuyutian.mytools.gateway.config.GatewayProperties;import com.yuyutian.mytools.gateway.model.MessagingGatewayModels.*;import org.springframework.http.*;import org.springframework.stereotype.Component;import org.springframework.web.client.*;import org.springframework.web.util.UriComponentsBuilder;import java.util.*;
/** Messaging 内部客户端。 */ @Component public class MessagingGatewayClient {private final RestTemplate template;private final GatewayProperties properties;
 /** 创建客户端。 @param template HTTP 模板 @param properties 配置 */ public MessagingGatewayClient(RestTemplate template,GatewayProperties properties){this.template=template;this.properties=properties;}
 /** 分页查询消息。 @param ownerId 所有者 @param afterId 游标 @param limit 数量 @param correlationId 关联标识 @return 消息页 */ public MessagePage list(long ownerId,UUID afterId,int limit,String correlationId){UriComponentsBuilder builder=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/inbound-messages").queryParam("ownerId",ownerId).queryParam("limit",limit);if(afterId!=null)builder.queryParam("afterId",afterId);return exchange(builder.toUriString(),MessagePage.class,correlationId);}
 /** 查询消息。 @param ownerId 所有者 @param id 消息 @param correlationId 关联标识 @return 消息 */ public MessageView view(long ownerId,UUID id,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/inbound-messages/"+id).queryParam("ownerId",ownerId).toUriString();return exchange(url,MessageView.class,correlationId);}
 /** 创建附件下载任务。 @param ownerId 所有者 @param messageId 消息 @param partId 分段 @param correlationId 关联标识 @return 附件任务 */ public AttachmentDownloadView createAttachment(long ownerId,UUID messageId,UUID partId,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/inbound-messages/"+messageId+"/parts/"+partId+"/download").queryParam("ownerId",ownerId).toUriString();return exchange(url,HttpMethod.POST,AttachmentDownloadView.class,correlationId);}
 /** 查询附件下载任务。 @param ownerId 所有者 @param jobId 作业 @param correlationId 关联标识 @return 附件任务 */ public AttachmentDownloadView attachment(long ownerId,UUID jobId,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/attachment-downloads/"+jobId).queryParam("ownerId",ownerId).toUriString();return exchange(url,HttpMethod.GET,AttachmentDownloadView.class,correlationId);}
 /** 取消附件下载任务。 @param ownerId 所有者 @param jobId 作业 @param correlationId 关联标识 @return 附件任务 */ public AttachmentDownloadView cancelAttachment(long ownerId,UUID jobId,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/attachment-downloads/"+jobId+"/cancel").queryParam("ownerId",ownerId).toUriString();return exchange(url,HttpMethod.POST,AttachmentDownloadView.class,correlationId);}
 /** 创建邮件投递。 @param ownerId 所有者 @param request 请求 @param correlationId 关联标识 @return 投递 */ public DeliveryView createEmail(long ownerId,CreateEmail request,String correlationId){Map<String,Object>body=new HashMap<>();body.put("ownerId",ownerId);body.put("idempotencyKey",request.idempotencyKey());body.put("channelType","EMAIL");body.put("recipient",request.recipient());body.put("subject",request.subject());body.put("body",request.body());return exchange(root()+"/internal/v1/deliveries",HttpMethod.POST,body,DeliveryView.class,correlationId);}
 /** 查询邮件投递。 @param ownerId 所有者 @param id 投递 @param correlationId 关联标识 @return 投递 */ public DeliveryView delivery(long ownerId,UUID id,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/deliveries/"+id).queryParam("ownerId",ownerId).toUriString();return exchange(url,HttpMethod.GET,null,DeliveryView.class,correlationId);}
 /** 取消邮件投递。 @param ownerId 所有者 @param id 投递 @param correlationId 关联标识 @return 投递 */ public DeliveryView cancelDelivery(long ownerId,UUID id,String correlationId){String url=UriComponentsBuilder.fromHttpUrl(root()+"/internal/v1/deliveries/"+id+"/cancel").queryParam("ownerId",ownerId).toUriString();return exchange(url,HttpMethod.POST,null,DeliveryView.class,correlationId);}
 private <T>T exchange(String url,Class<T>type,String correlationId){return exchange(url,HttpMethod.GET,type,correlationId);}
 private <T>T exchange(String url,HttpMethod method,Class<T>type,String correlationId){return exchange(url,method,null,type,correlationId);}
 private <T>T exchange(String url,HttpMethod method,Object body,Class<T>type,String correlationId){try{T value=template.exchange(url,method,entity(body,correlationId),type).getBody();if(value==null)throw new GatewayDownstreamException();return value;}catch(HttpStatusCodeException exception){if(exception.getStatusCode().value()==404)throw new GatewayNotFoundException();if(exception.getStatusCode().is4xxClientError())throw new GatewayBadRequestException();throw new GatewayDownstreamException();}catch(ResourceAccessException exception){throw new GatewayDownstreamException();}}
 private HttpEntity<Void> entity(String correlationId){if(properties.messagingToken()==null||properties.messagingToken().isBlank())throw new GatewayUnauthorizedException();HttpHeaders headers=new HttpHeaders();headers.setBearerAuth(properties.messagingToken());headers.set("X-Correlation-Id",correlationId);return new HttpEntity<>(headers);}
 private HttpEntity<?> entity(Object body,String correlationId){if(properties.messagingToken()==null||properties.messagingToken().isBlank())throw new GatewayUnauthorizedException();HttpHeaders headers=new HttpHeaders();headers.setBearerAuth(properties.messagingToken());headers.set("X-Correlation-Id",correlationId);headers.setContentType(MediaType.APPLICATION_JSON);return new HttpEntity<>(body,headers);}
 private String root(){return properties.messagingUrl().replaceAll("/+$","");}
}
