package com.yuyutian.mytools.catalog.service;
import com.yuyutian.mytools.catalog.model.CatalogModels.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.security.NoSuchAlgorithmException;import java.time.Instant;import java.util.HexFormat;import java.util.List;import java.util.UUID;import static org.assertj.core.api.Assertions.*;
/** 应用目录迁移测试。 */ @SpringBootTest class AppCatalogServiceTest {@Autowired private AppCatalogService service;
 @Test void shouldDryRunImportReplayAndReconcileLegacyAggregate(){LegacyAppImport dry=request(true,"catalog-v1");assertThat(service.importLegacy(dry).accepted()).isEqualTo(1);assertThat(service.list()).isEmpty();LegacyAppImport applied=request(false,"catalog-v1");ImportResult result=service.importLegacy(applied);assertThat(result.accepted()).isEqualTo(1);assertThat(service.importLegacy(applied).skipped()).isEqualTo(1);assertThat(service.list()).singleElement().satisfies(value->{assertThat(value.legacyId()).isEqualTo("100");assertThat(value.versionCount()).isEqualTo(1);assertThat(value.fileCount()).isEqualTo(1);});MigrationEvidence evidence=service.migrationEvidence("catalog-v1");assertThat(evidence.appCount()).isEqualTo(1);assertThat(evidence.versionCount()).isEqualTo(1);assertThat(evidence.fileCount()).isEqualTo(1);assertThat(evidence.collectionSha256()).isEqualTo(collectionDigest("100",result.digestSha256()));Reconciliation reconciliation=service.reconciliation();assertThat(reconciliation.appCount()).isEqualTo(1);assertThat(reconciliation.versionCount()).isEqualTo(1);assertThat(reconciliation.fileCount()).isEqualTo(1);assertThat(reconciliation.unresolvedFileCount()).isEqualTo(1);assertThat(reconciliation.digestSha256()).hasSize(64);}
 @Test void shouldRejectMissingVersionRelationAndChangedReplay(){LegacyApp app=new LegacyApp("200",2,"Broken","app","1",null,null,null,null,"DRAFT",Instant.EPOCH,Instant.EPOCH);LegacyFile file=new LegacyFile("201","missing","binary","x","/legacy/x",1,Instant.EPOCH);assertThatThrownBy(()->service.importLegacy(new LegacyAppImport("catalog-v2",true,app,List.of(),List.of(file)))).isInstanceOf(IllegalArgumentException.class);LegacyAppImport original=request(false,"catalog-conflict");service.importLegacy(original);LegacyApp changed=new LegacyApp("100",1,"Changed","app","1.0",null,"content",null,null,"PUBLISHED",Instant.EPOCH,Instant.EPOCH);assertThat(service.importLegacy(new LegacyAppImport("catalog-conflict",false,changed,original.versions(),original.files())).rejected()).isEqualTo(1);}
 @Test void shouldHideUnpublishedEntries(){LegacyApp draft=new LegacyApp("300",3,"Draft","app","1",null,null,null,null,"DRAFT",Instant.EPOCH,Instant.EPOCH);service.importLegacy(new LegacyAppImport("catalog-draft",false,draft,List.of(),List.of()));assertThat(service.list()).allMatch(value->value.status().equals("PUBLISHED"));}
 @Test void shouldPageAndIdempotentlyBindMigratedFile(){service.importLegacy(request(false,"catalog-files"));UnresolvedFile file=service.unresolvedFiles(null,100).items().stream().filter(value->value.legacyId().equals("120")).findFirst().orElseThrow();UUID assetId=UUID.randomUUID();BindFileAsset request=new BindFileAsset("120",assetId,"a".repeat(64),"storage://managed/app-catalog/120/a.zip",12);assertThat(service.bindFileAsset(file.id(),request).skipped()).isFalse();assertThat(service.bindFileAsset(file.id(),request).skipped()).isTrue();assertThat(service.reconciliation().unresolvedFileCount()).isZero();assertThatThrownBy(()->service.bindFileAsset(file.id(),new BindFileAsset("120",UUID.randomUUID(),"b".repeat(64),"storage://managed/other",12))).isInstanceOf(IllegalStateException.class);}
 private String collectionDigest(String...values){try{MessageDigest digest=MessageDigest.getInstance("SHA-256");for(String value:values){byte[]data=value.getBytes(StandardCharsets.UTF_8);digest.update(ByteBuffer.allocate(4).putInt(data.length).array());digest.update(data);}return HexFormat.of().formatHex(digest.digest());}catch(NoSuchAlgorithmException exception){throw new IllegalStateException(exception);}}
 private LegacyAppImport request(boolean dryRun,String key){LegacyApp app=new LegacyApp("100",1,"Sample","app","1.0",null,"content",null,null,"PUBLISHED",Instant.EPOCH,Instant.EPOCH);LegacyVersion version=new LegacyVersion("110","1.0","content","120",Instant.EPOCH);LegacyFile file=new LegacyFile("120","110","binary","sample.zip","/legacy/sample.zip",12,Instant.EPOCH);return new LegacyAppImport(key,dryRun,app,List.of(version),List.of(file));}}
