package com.yuyutian.mytools.task.scheduler.common;

/**
 * 调度服务错误码。
 */
public enum ErrorCode {
    UNAUTHORIZED,
    NODE_REGISTRATION_FORBIDDEN,
    INVALID_REQUEST,
    IDEMPOTENCY_CONFLICT,
    TASK_PARAMETER_SCHEMA_INVALID,
    TASK_RESULT_SCHEMA_INVALID,
    EXECUTION_LEASE_LOST,
    REPORT_CONFLICT,
    EXECUTION_STATE_CONFLICT,
    CHECKPOINT_CONFLICT,
    INTERNAL_ERROR
}
