package com.yuyutian.mytools.catalog.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.yuyutian.mytools.catalog.model.CatalogModels.*;import com.yuyutian.mytools.catalog.repository.AppCatalogRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Instant;import java.util.*;
/** 应用目录领域服务。 */ @Service public class AppCatalogService {private final AppCatalogRepository repository;private final ObjectMapper mapper;/** 创建服务。 @param repository 仓储 @param mapper JSON */ public AppCatalogService(AppCatalogRepository repository,ObjectMapper mapper){this.repository=repository;this.mapper=mapper;}
 /** 预检或导入旧应用。 @param request 请求 @return 结果 */ @Transactional public ImportResult importLegacy(LegacyAppImport request){validateRelations(request);String digest=digest(request.app(),request.versions(),request.files());String existing=repository.migrationDigest(request.app().legacyId());if(existing!=null){if(!existing.equals(digest))return new ImportResult(request.dryRun(),0,0,1,digest);return new ImportResult(request.dryRun(),0,1,0,digest);}if(!request.dryRun())repository.insert(request,digest,Instant.now());return new ImportResult(request.dryRun(),1,0,0,digest);}
 /** 查询已发布应用目录。 @return 目录 */ @Transactional(readOnly=true) public List<CatalogView> list(){return repository.list();}
 /** 返回确定性数量对账。 @return 对账 */ @Transactional(readOnly=true) public Reconciliation reconciliation(){int apps=repository.count("app_catalog_entry"),versions=repository.count("app_catalog_version"),files=repository.count("app_catalog_file"),unresolved=repository.unresolvedFiles();return new Reconciliation(apps,versions,files,unresolved,digest(apps,versions,files,unresolved));}
 /** 返回指定迁移键的精确应用聚合证据。 @param migrationKey 迁移键 @return 证据 */ @Transactional(readOnly=true) public MigrationEvidence migrationEvidence(String migrationKey){if(migrationKey==null||!migrationKey.matches("[A-Za-z0-9._:-]{1,128}"))throw new IllegalArgumentException("catalog migration key is invalid");List<AppCatalogRepository.MigrationRecord>records=repository.migrationEvidence(migrationKey);MessageDigest collection=sha256();int versions=0,files=0;for(var record:records){update(collection,record.legacyAppId(),record.payloadSha256());versions+=record.versionCount();files+=record.fileCount();}return new MigrationEvidence(migrationKey,records.size(),versions,files,HexFormat.of().formatHex(collection.digest()));}
 /** 分页返回未迁移文件。 @param afterId 起始标识 @param limit 页大小 @return 文件页 */ @Transactional(readOnly=true) public UnresolvedFilePage unresolvedFiles(UUID afterId,int limit){if(limit<1||limit>200)throw new IllegalArgumentException("catalog file migration limit is invalid");List<UnresolvedFile>values=repository.unresolvedFiles(afterId,limit+1);List<UnresolvedFile>page=values.stream().limit(limit).toList();UUID next=values.size()>limit&&!page.isEmpty()?page.getLast().id():null;return new UnresolvedFilePage(page,next);}
 /** 幂等绑定已迁移文件资产。 @param id 文件标识 @param request 请求 @return 绑定结果 */ @Transactional public BindFileAssetResult bindFileAsset(UUID id,BindFileAsset request){var current=repository.fileAsset(id).orElseThrow(()->new IllegalArgumentException("catalog file not found"));if(!current.legacyId().equals(request.legacyId())||current.fileSize()!=request.fileSize())throw new IllegalStateException("catalog file migration identity conflicts");if(current.assetId()!=null)return existingBinding(id,request,current);if(repository.bindFileAsset(id,request,Instant.now()))return new BindFileAssetResult(id,request.assetId(),request.contentSha256(),request.storageUri(),false);return existingBinding(id,request,repository.fileAsset(id).orElseThrow());}
 private BindFileAssetResult existingBinding(UUID id,BindFileAsset request,AppCatalogRepository.FileAssetBinding current){boolean same=Objects.equals(current.assetId(),request.assetId().toString())&&Objects.equals(current.contentSha256(),request.contentSha256())&&Objects.equals(current.storageUri(),request.storageUri());if(!same)throw new IllegalStateException("catalog file asset binding conflicts");return new BindFileAssetResult(id,request.assetId(),request.contentSha256(),request.storageUri(),true);}
 private void validateRelations(LegacyAppImport request){Set<String>versionIds=new HashSet<>(),fileIds=new HashSet<>();for(LegacyVersion value:request.versions())if(!versionIds.add(value.legacyId()))throw new IllegalArgumentException("catalog version is duplicated");for(LegacyFile value:request.files()){if(!fileIds.add(value.legacyId()))throw new IllegalArgumentException("catalog file is duplicated");if(value.legacyVersionId()!=null&&!versionIds.contains(value.legacyVersionId()))throw new IllegalArgumentException("catalog file version is missing");}}
 private String digest(Object...values){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(mapper.writeValueAsBytes(values)));}catch(NoSuchAlgorithmException|java.io.IOException exception){throw new IllegalStateException("catalog digest failed",exception);}}
 private MessageDigest sha256(){try{return MessageDigest.getInstance("SHA-256");}catch(NoSuchAlgorithmException exception){throw new IllegalStateException("SHA-256 is unavailable",exception);}}
 private void update(MessageDigest digest,String...values){for(String value:values){byte[]data=value.getBytes(StandardCharsets.UTF_8);digest.update(ByteBuffer.allocate(4).putInt(data.length).array());digest.update(data);}}
}
