package com.yuyutian.mytools.catalog.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.yuyutian.mytools.catalog.model.CatalogModels.*;import com.yuyutian.mytools.catalog.repository.AppCatalogRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.security.*;import java.time.Instant;import java.util.*;
/** 应用目录领域服务。 */ @Service public class AppCatalogService {private final AppCatalogRepository repository;private final ObjectMapper mapper;/** 创建服务。 @param repository 仓储 @param mapper JSON */ public AppCatalogService(AppCatalogRepository repository,ObjectMapper mapper){this.repository=repository;this.mapper=mapper;}
 /** 预检或导入旧应用。 @param request 请求 @return 结果 */ @Transactional public ImportResult importLegacy(LegacyAppImport request){validateRelations(request);String digest=digest(request.app(),request.versions(),request.files());String existing=repository.migrationDigest(request.app().legacyId());if(existing!=null){if(!existing.equals(digest))return new ImportResult(request.dryRun(),0,0,1,digest);return new ImportResult(request.dryRun(),0,1,0,digest);}if(!request.dryRun())repository.insert(request,digest,Instant.now());return new ImportResult(request.dryRun(),1,0,0,digest);}
 /** 查询已发布应用目录。 @return 目录 */ @Transactional(readOnly=true) public List<CatalogView> list(){return repository.list();}
 /** 返回确定性数量对账。 @return 对账 */ @Transactional(readOnly=true) public Reconciliation reconciliation(){int apps=repository.count("app_catalog_entry"),versions=repository.count("app_catalog_version"),files=repository.count("app_catalog_file"),unresolved=repository.unresolvedFiles();return new Reconciliation(apps,versions,files,unresolved,digest(apps,versions,files,unresolved));}
 private void validateRelations(LegacyAppImport request){Set<String>versionIds=new HashSet<>(),fileIds=new HashSet<>();for(LegacyVersion value:request.versions())if(!versionIds.add(value.legacyId()))throw new IllegalArgumentException("catalog version is duplicated");for(LegacyFile value:request.files()){if(!fileIds.add(value.legacyId()))throw new IllegalArgumentException("catalog file is duplicated");if(value.legacyVersionId()!=null&&!versionIds.contains(value.legacyVersionId()))throw new IllegalArgumentException("catalog file version is missing");}}
 private String digest(Object...values){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(mapper.writeValueAsBytes(values)));}catch(NoSuchAlgorithmException|java.io.IOException exception){throw new IllegalStateException("catalog digest failed",exception);}}
}
