package com.yuyutian.mytools.messaging.service;
import com.fasterxml.jackson.databind.ObjectMapper;import com.yuyutian.mytools.messaging.model.*;import com.yuyutian.mytools.messaging.repository.SupportFeedbackRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.Instant;import java.util.*;
/** 问题反馈迁移服务。 */ @Service public class SupportFeedbackMigrationService {private final SupportFeedbackRepository repository;private final ObjectMapper mapper;/** 创建服务。 @param repository 仓储 @param mapper JSON */ public SupportFeedbackMigrationService(SupportFeedbackRepository repository,ObjectMapper mapper){this.repository=repository;this.mapper=mapper;}
 /** 预检或导入反馈批次。 @param batch 批次 @return 结果 */ @Transactional public LegacyFeedbackMigrationResult migrate(LegacyFeedbackBatch batch){int accepted=0,skipped=0,rejected=0;MessageDigest collection=sha256();Set<Long>seen=new HashSet<>();for(LegacyFeedbackItem item:batch.items()){String digest=digest(item);update(collection,Long.toString(item.legacyId()),digest);if(!seen.add(item.legacyId())){skipped++;continue;}String existing=repository.digest(item.legacyId());if(existing==null){accepted++;if(!batch.dryRun())repository.insert(batch.migrationKey(),item,digest,Instant.now());}else if(existing.equals(digest))skipped++;else rejected++;}return new LegacyFeedbackMigrationResult(batch.dryRun(),accepted,skipped,rejected,HexFormat.of().formatHex(collection.digest()));}
 /** 对账一个迁移键。 @param key 迁移键 @return 对账 */ @Transactional(readOnly=true) public FeedbackReconciliation reconcile(String key){MessageDigest digest=sha256();List<String>values=repository.migrationEvidence(key);for(String value:values){String[]parts=value.split("\\|",2);update(digest,parts[0],parts[1]);}return new FeedbackReconciliation(values.size(),HexFormat.of().formatHex(digest.digest()));}
 private String digest(Object value){try{return HexFormat.of().formatHex(sha256().digest(mapper.writeValueAsBytes(value)));}catch(java.io.IOException exception){throw new IllegalStateException("feedback digest failed",exception);}}
 private MessageDigest sha256(){try{return MessageDigest.getInstance("SHA-256");}catch(NoSuchAlgorithmException exception){throw new IllegalStateException("SHA-256 unavailable",exception);}}
 private void update(MessageDigest digest,String...values){for(String value:values){byte[]data=value.getBytes(StandardCharsets.UTF_8);digest.update(ByteBuffer.allocate(4).putInt(data.length).array());digest.update(data);}}
}
