package com.yuyutian.mytools.storage.model;

/**
 * 存储网关统一错误码。
 */
public enum ErrorCode {
    ROOT_NOT_FOUND("STORAGE_001"),
    IDEMPOTENCY_CONFLICT("STORAGE_002"),
    UPLOAD_TOO_LARGE("STORAGE_003"),
    PATH_INVALID("STORAGE_004"),
    UPLOAD_CONFLICT("STORAGE_005"),
    CONTENT_MISMATCH("STORAGE_006"),
    IO_FAILURE("STORAGE_007"),
    TARGET_CONFLICT("STORAGE_008"),
    UPLOAD_NOT_FOUND("STORAGE_009"),
    INTERNAL_UNAUTHORIZED("STORAGE_010"),
    PROVIDER_NOT_FOUND("STORAGE_011"),
    PROVIDER_CONFLICT("STORAGE_012"),
    PROVIDER_INVALID("STORAGE_013"),
    REMOTE_FAILURE("STORAGE_014"),
    OPERATION_NOT_FOUND("STORAGE_015"),
    OPERATION_CONFLICT("STORAGE_016"),
    OPERATION_STATE_INVALID("STORAGE_017"),
    TICKET_NOT_FOUND("STORAGE_018"),
    TICKET_INVALID("STORAGE_019"),
    TICKET_STATE_CONFLICT("STORAGE_020"),
    CHECKSUM_NOT_FOUND("STORAGE_021"),
    MOVE_VERIFICATION_FAILED("STORAGE_022"),
    MOVE_SOURCE_DELETE_FAILED("STORAGE_023"),
    MOVE_COMPENSATION_FAILED("STORAGE_024"),
    MOVE_RECOVERY_REQUIRED("STORAGE_025"),
    SECRET_UNAVAILABLE("STORAGE_026"),
    REMOTE_LIST_LIMIT("STORAGE_027");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    /**
     * 返回稳定错误码。
     *
     * @return 错误码
     */
    public String code() {
        return code;
    }
}
