CREATE TABLE IF NOT EXISTS ebook_metadata (
    local_file_id BIGINT PRIMARY KEY COMMENT '本地文件ID',
    file_hash VARCHAR(64) COMMENT '索引时文件哈希',
    metadata_version INT NOT NULL DEFAULT 1 COMMENT '元数据结构版本',
    status VARCHAR(20) NOT NULL COMMENT '索引状态',
    error_message VARCHAR(500) COMMENT '索引错误',
    failure_count INT NOT NULL DEFAULT 0 COMMENT '连续失败次数',
    retry_after TIMESTAMP NULL COMMENT '失败后下次重试时间',
    title VARCHAR(500) NOT NULL COMMENT '书名',
    author VARCHAR(300) NOT NULL DEFAULT '' COMMENT '作者',
    description TEXT COMMENT '简介',
    language VARCHAR(32) NOT NULL DEFAULT '' COMMENT '语言',
    category VARCHAR(100) NOT NULL DEFAULT '' COMMENT '分类',
    completion_status VARCHAR(32) NOT NULL DEFAULT '' COMMENT '完结状态',
    chapter_count INT COMMENT '章节数',
    word_count BIGINT COMMENT '字数',
    cover_path VARCHAR(1024) COMMENT '封面路径',
    parser_name VARCHAR(100) NOT NULL COMMENT '解析器名称',
    model_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '补齐模型名称',
    model_version VARCHAR(100) NOT NULL DEFAULT '' COMMENT '补齐模型版本',
    indexed_at TIMESTAMP NOT NULL COMMENT '索引时间',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_ebook_metadata_title (title),
    INDEX idx_ebook_metadata_author (author),
    INDEX idx_ebook_metadata_status (status),
    INDEX idx_ebook_metadata_retry (status, retry_after)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='电子书领域元数据';
