package com.yuyutian.mytools.dshconnector.controller;import com.yuyutian.mytools.dshconnector.model.DshModels.*;import com.yuyutian.mytools.dshconnector.service.DshSessionService;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.List;
/** DSH 会话内部接口。 */ @Validated @RestController @RequestMapping("/internal/v1/dsh/sessions") public class DshSessionController {private final DshSessionService service;private final String token;/** 创建控制器。 @param service 服务 @param token 令牌 */ public DshSessionController(DshSessionService service,@Value("${dsh-connector.internal-token}")String token){this.service=service;this.token=token;}
 /** 迁移旧绑定。 @param authorization 授权 @param batch 批次 @return 结果 */ @PostMapping("/migrations/legacy") public MigrationResult migrate(@RequestHeader("Authorization")String authorization,@Valid @RequestBody MigrationBatch batch){authorize(authorization);return service.migrate(batch);}
 /** 查询用户会话。 @param authorization 授权 @param ownerId 所有者 @return 会话 */ @GetMapping public List<BindingView> list(@RequestHeader("Authorization")String authorization,@RequestParam @Positive long ownerId){authorize(authorization);return service.list(ownerId);}
 /** 推进会话序号。 @param authorization 授权 @param sessionId 会话 @param ownerId 所有者 @param sequence 序号 */ @PutMapping("/{sessionId}/sequence") public void advance(@RequestHeader("Authorization")String authorization,@PathVariable @Size(max=128)String sessionId,@RequestParam @Positive long ownerId,@RequestParam @PositiveOrZero long sequence){authorize(authorization);service.advance(ownerId,sessionId,sequence);}
 /** 归档会话。 @param authorization 授权 @param sessionId 会话 @param ownerId 所有者 */ @DeleteMapping("/{sessionId}") public void archive(@RequestHeader("Authorization")String authorization,@PathVariable @Size(max=128)String sessionId,@RequestParam @Positive long ownerId){authorize(authorization);service.archive(ownerId,sessionId);}
 /** 对账迁移。 @param authorization 授权 @param migrationKey 迁移键 @return 对账 */ @GetMapping("/migrations/legacy/reconciliation") public Reconciliation reconcile(@RequestHeader("Authorization")String authorization,@RequestParam @Pattern(regexp="[A-Za-z0-9._:-]{1,128}")String migrationKey){authorize(authorization);return service.reconcile(migrationKey);}
 private void authorize(String authorization){String supplied=authorization!=null&&authorization.startsWith("Bearer ")?authorization.substring(7):"";if(token.isBlank()||!MessageDigest.isEqual(token.getBytes(StandardCharsets.UTF_8),supplied.getBytes(StandardCharsets.UTF_8)))throw new SecurityException("dsh authorization failed");}
}
