package com.yuyutian.mytools.catalog.repository;
import com.yuyutian.mytools.catalog.model.CatalogModels.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Repository;import java.sql.Timestamp;import java.time.Instant;import java.util.*;
/** 应用目录仓储。 */ @Repository public class AppCatalogRepository {private final JdbcTemplate jdbc;/** 创建仓储。 @param jdbc JDBC */ public AppCatalogRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 /** 查询旧应用摘要。 @param legacyId 旧标识 @return 摘要 */ public String migrationDigest(String legacyId){return jdbc.query("SELECT payload_sha256 FROM app_catalog_migration_item WHERE legacy_app_id=?",(rs,row)->rs.getString(1),legacyId).stream().findFirst().orElse(null);}
 /** 导入一个旧应用聚合。 @param request 请求 @param digest 摘要 @param now 时间 */ public void insert(LegacyAppImport request,String digest,Instant now){LegacyApp app=request.app();String entryId=UUID.randomUUID().toString();jdbc.update("INSERT INTO app_catalog_entry VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",entryId,app.legacyId(),app.ownerId(),app.name(),app.appType(),app.currentVersion(),app.legacyThumbnailId(),app.content(),app.installCommand(),app.downloadUrl(),app.status(),Timestamp.from(app.createdAt()),Timestamp.from(app.updatedAt()));Map<String,String>versions=new HashMap<>();for(LegacyVersion value:request.versions()){String id=UUID.randomUUID().toString();versions.put(value.legacyId(),id);jdbc.update("INSERT INTO app_catalog_version VALUES (?,?,?,?,?,?,?)",id,entryId,value.legacyId(),value.version(),value.content(),value.legacyFileId(),Timestamp.from(value.createdAt()));}for(LegacyFile value:request.files())jdbc.update("INSERT INTO app_catalog_file VALUES (?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),entryId,value.legacyVersionId()==null?null:versions.get(value.legacyVersionId()),value.legacyId(),value.fileType(),value.fileName(),value.legacyStoragePath(),value.fileSize(),null,Timestamp.from(value.createdAt()));jdbc.update("INSERT INTO app_catalog_migration_item VALUES (?,?,?,?)",app.legacyId(),digest,request.migrationKey(),Timestamp.from(now));}
 /** 查询目录。 @return 目录 */ public List<CatalogView> list(){return jdbc.query("SELECT e.*,COUNT(DISTINCT v.id) version_count,COUNT(DISTINCT f.id) file_count FROM app_catalog_entry e LEFT JOIN app_catalog_version v ON v.entry_id=e.id LEFT JOIN app_catalog_file f ON f.entry_id=e.id GROUP BY e.id ORDER BY e.created_at,e.id",(rs,row)->new CatalogView(UUID.fromString(rs.getString("id")),rs.getString("legacy_id"),rs.getLong("owner_id"),rs.getString("name"),rs.getString("app_type"),rs.getString("current_version"),rs.getString("status"),rs.getInt("version_count"),rs.getInt("file_count")));}
 /** 返回表计数。 @param table 表 @return 数量 */ public int count(String table){if(!Set.of("app_catalog_entry","app_catalog_version","app_catalog_file").contains(table))throw new IllegalArgumentException("catalog table is invalid");Integer value=jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class);return value==null?0:value;}
 /** 返回未绑定资产的文件数。 @return 数量 */ public int unresolvedFiles(){Integer value=jdbc.queryForObject("SELECT COUNT(*) FROM app_catalog_file WHERE asset_id IS NULL",Integer.class);return value==null?0:value;}
}
