const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript');
const source = fs.readFileSync('app/entry/src/main/ets/features/reader/ReaderDirectoryCache.ets', 'utf8');
const context = { exports: {} };
vm.runInNewContext(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, context);
const cache = new context.exports.ReaderDirectoryCache();
const key = cache.key('owner', 'endpoint', 'source', '/', '', false);
const snapshot = { items: [{ path: '/a' }], page: 2, total: 90, loadedCount: 80, hasMore: true, savedAt: 1000 };
cache.put(key, snapshot);
snapshot.items.push({ path: '/b' });
assert.equal(cache.get(key, 2000).items.length, 1);
assert.equal(cache.get(key, 2000).page, 2);
assert.notEqual(key, cache.key('other', 'endpoint', 'source', '/', '', false));
assert.notEqual(key, cache.key('owner', 'other', 'source', '/', '', false));
assert.notEqual(key, cache.key('owner', 'endpoint', 'source', '/', 'search', false));
assert.notEqual(key, cache.key('owner', 'endpoint', 'source', '/', '', true));
assert.equal(cache.get(key, 601001), undefined);
cache.put(key, snapshot); assert.equal(cache.get(key, 999), undefined);
for (let i = 0; i < 13; i++) cache.put(String(i), snapshot);
assert.equal(cache.get('0', 2000), undefined);
assert.ok(cache.get('12', 2000));
cache.put('large', { ...snapshot, items: Array(201).fill({}) });
assert.equal(cache.get('large', 2000), undefined);
cache.clear(); assert.equal(cache.get('12', 2000), undefined);
const index = fs.readFileSync('app/entry/src/main/ets/pages/Index.ets', 'utf8');
assert.match(index, /LoadRemoteBookDirectory\(false\)/);
assert.match(index, /readerRepository\.restore\(context, scope\)/);
assert.match(index, /if \(this\.bookModeIndex === 0\) return this\.books\.filter/);
assert.match(index, /if \(this\.bookModeIndex === 2\) return this\.books\.filter/);
console.log('Reader cache isolation, expiry, pagination, bounds and local snapshot checks passed');
