packages:
  - 'packages/*'
allowBuilds:
  - '@parcel/watcher'
  - 'esbuild'
  - 'simple-git-hooks'
  - 'vue-demi'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - 'esbuild'
  - 'simple-git-hooks'
  - 'vue-demi'
