package com.yuyutian.mytools.pikpak.common;

/** PikPak 连接器统一错误码。 */
public enum ErrorCode {
    ACCOUNT_CONFLICT("PIKPAK_001"), ACCOUNT_NOT_FOUND("PIKPAK_002"),
    OPERATION_NOT_FOUND("PIKPAK_003"), OPERATION_CONCURRENT_UPDATE("PIKPAK_004"),
    RCLONE_ENDPOINT_INVALID("PIKPAK_005"), RCLONE_LIST_INVALID("PIKPAK_006"),
    RCLONE_JOB_INVALID("PIKPAK_007"), REMOTE_KEY_INVALID("PIKPAK_008"),
    REMOTE_PATH_INVALID("PIKPAK_009"), RCLONE_FAILURE("PIKPAK_010"),
    INTERNAL_UNAUTHORIZED("PIKPAK_011"), ACCOUNT_ROOT_CONFLICT("PIKPAK_012"),
    ACCOUNT_DISABLED("PIKPAK_013"), OPERATION_IDEMPOTENCY_CONFLICT("PIKPAK_014"),
    OPERATION_STATE_INVALID("PIKPAK_015"), INPUT_DIGEST_CONFLICT("PIKPAK_016"),
    MOVE_FAILED("PIKPAK_017"), CONNECTOR_DISABLED("PIKPAK_018"),
    MAGNET_INVALID("PIKPAK_019"), ACCOUNT_ROOT_INVALID("PIKPAK_020"),
    REQUEST_INVALID("PIKPAK_021"), INTERNAL_FAILURE("PIKPAK_022");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    /** 返回稳定错误码。 @return 错误码 */
    public String code() {
        return code;
    }
}
