#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TEST_DIR="$(mktemp -d)"
trap 'rm -rf "$TEST_DIR"' EXIT
TSC_BIN="/Applications/DevEco-Studio.app/Contents/tools/hvigor/hvigor/node_modules/typescript/bin/tsc"
POLICY="$APP_DIR/entry/src/main/ets/features/reader/RemoteBookDownloadPolicy.ets"
LOADER="$APP_DIR/entry/src/main/ets/features/reader/ReaderContentLoader.ets"

cp "$POLICY" "$TEST_DIR/RemoteBookDownloadPolicy.ts"
node "$TSC_BIN" "$TEST_DIR/RemoteBookDownloadPolicy.ts" --target ES2020 --module commonjs \
  --outDir "$TEST_DIR/output" --skipLibCheck
node "$APP_DIR/tests/remote_book_download_policy_test.cjs" "$TEST_DIR/output/RemoteBookDownloadPolicy.js"

grep -Fq 'this.remoteDownloadPolicy.url(url)' "$LOADER"
grep -Fq 'this.remoteDownloadPolicy.requestHeaders(requestHeaders)' "$LOADER"
grep -Fq "ReaderContentLoader.MAX_LARGE_TEXT_BYTES, 'text'" "$LOADER"
grep -Fq 'this.remoteDownloadPolicy.headers(headers, maxBytes, kind)' "$LOADER"
grep -Fq "'archive', requestHeaders" "$LOADER"
grep -Fq "'远程PDF', 'pdf'" "$LOADER"
grep -Fq "'远程MOBI', 'mobi'" "$LOADER"
grep -Fq 'request.requestInStream(safeUrl' "$LOADER"
grep -Fq 'if (!completed) this.removePartialDownload(path)' "$LOADER"
grep -Fq 'private removePartialDownload(path: string): void' "$LOADER"
grep -Fq 'const written = this.writeRemoteBookChunk(file, buffer)' "$LOADER"
grep -Fq 'cachedFingerprint !== `${received}-${receivedHash >>> 0}`' "$LOADER"
grep -Fq 'declaredLength !== undefined && declaredLength !== received' "$LOADER"
grep -Fq 'this.remoteDownloadPolicy.payloadError(' "$LOADER"
grep -Fq "this.validatePayloadSignature(archivePath, stat.size, 'archive')" "$LOADER"
grep -Fq "this.validatePayloadSignature(path, stat.size, 'pdf')" "$LOADER"
grep -Fq "this.validatePayloadSignature(path, stat.size, 'mobi')" "$LOADER"
grep -Fq 'this.inspectZipArchive(archivePath, format)' "$LOADER"
grep -Fq "if (format === 'epub' && !epubMimetypeValid)" "$LOADER"
grep -Fq "this.assertSafeEpubMarkup(container, 'container.xml')" "$LOADER"
grep -Fq "this.assertSafeEpubMarkup(packageXml, 'OPF')" "$LOADER"
grep -Fq "this.assertSafeEpubMarkup(html, '章节')" "$LOADER"
grep -Fq 'chapterSize > ReaderContentLoader.MAX_EPUB_CHAPTER_BYTES' "$LOADER"
grep -Fq 'totalChapterBytes > ReaderContentLoader.MAX_EPUB_TEXT_BYTES' "$LOADER"
grep -Fq 'totalCharacters > ReaderContentLoader.MAX_EPUB_TEXT_CHARACTERS' "$LOADER"
grep -Fq 'this.validateEpubHtmlShape(html)' "$LOADER"
grep -Fq 'count > ReaderContentLoader.MAX_EPUB_TAGS' "$LOADER"
grep -Fq 'match[2].length > ReaderContentLoader.MAX_EPUB_ATTRIBUTES' "$LOADER"
grep -Fq 'manifestItems > ReaderContentLoader.MAX_EPUB_MANIFEST_ITEMS' "$LOADER"
grep -Fq 'spineItems > ReaderContentLoader.MAX_EPUB_SPINE_ITEMS' "$LOADER"
grep -Fq 'itemMatch[1].length > ReaderContentLoader.MAX_EPUB_ATTRIBUTES' "$LOADER"
grep -Fq 'this.validEpubRelativeReference(href)' "$LOADER"
grep -Fq 'spineIds.has(idref)' "$LOADER"
grep -Fq 'private validEpubIdentifier(value: string): boolean' "$LOADER"
grep -Fq "name.normalize('NFC') !== name" "$LOADER"
grep -Fq "decoded.normalize('NFC') !== decoded" "$LOADER"
grep -Fq "const foldedName = normalized.toLocaleLowerCase('en-US')" "$LOADER"
grep -Fq 'foldedNames.has(foldedName)' "$LOADER"
grep -Fq 'con|prn|aux|nul|com[1-9]|lpt[1-9]' "$LOADER"
grep -Fq '/[. ]$/.test(segment)' "$LOADER"
grep -Fq '图书容器父路径已被声明为文件' "$LOADER"
grep -Fq 'directoryNames.has(structuralFolded)' "$LOADER"
grep -Fq 'compressedSize > centralOffset - dataOffset' "$LOADER"
grep -Fq 'ZIP条目数据区重叠' "$LOADER"
grep -Fq 'localCrc32 !== crc32' "$LOADER"
grep -Fq 'ZIP流式条目本地头必须使用空CRC和尺寸' "$LOADER"
grep -Fq 'private validateZipDataDescriptor(' "$LOADER"
grep -Fq 'ZIP数据描述符与中央目录不一致' "$LOADER"
grep -Fq 'this.validateZipFlags(flags, compression)' "$LOADER"
grep -Fq 'ZIP条目包含不支持的通用标志位' "$LOADER"
grep -Fq 'this.validateZipExtraFields(central.subarray' "$LOADER"
grep -Fq 'ZIP扩展字段长度越界' "$LOADER"
grep -Fq '暂不支持ZIP64扩展字段' "$LOADER"
grep -Fq 'const archiveManifest = this.inspectZipArchive(archivePath, format)' "$LOADER"
grep -Fq 'manifestFiles.set(normalized, uncompressedSize)' "$LOADER"
grep -Fq 'new Map<string, number>(archiveManifest.files)' "$LOADER"
grep -Fq '解压产生中央目录未声明的文件' "$LOADER"
grep -Fq '解压文件尺寸与中央目录不一致' "$LOADER"
grep -Fq '中央目录声明的文件未被完整解压' "$LOADER"
grep -Fq 'const stat = fs.lstatSync(path)' "$LOADER"
grep -Fq '解压内容包含符号链接' "$LOADER"
grep -Fq 'this.extractedFilePaths = new Set<string>(files)' "$LOADER"
grep -Fq 'if (!this.extractedFilePaths.has(path)) return fallback' "$LOADER"
grep -Fq '!this.extractedFilePaths.has(path)' "$LOADER"

echo "Remote book download integration policy tests passed"
